name: Regression Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    tests:
      name: Run regression tests
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Set system to non-interactive mode
          run: export DEBIAN_FRONTEND=noninteractive
        - name: Install dependencies
          run: |
            sudo apt-get update -qq
            sudo apt-get install -qq --no-install-recommends tzdata
            sudo apt-get install -qq git
            sudo apt-get install -qq make cmake g++
            sudo apt-get install -qq openssh-client
            sudo apt-get install -qq python3 python3-numpy
        - name: Run test scripts
          run: |
            cd tst/regression
            python3 regression_test.py
